[package]
name = "rusty-req"
version = "0.1.4"
edition = "2021"

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
pyo3-asyncio = { version = "0.20", features = ["tokio-runtime"] }
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
chrono = "0.4"
futures = "0.3"
once_cell = "1.18"