[build-system]
requires = [ "maturin==1.9.2",]
build-backend = "maturin"

[project]
name = "rusty-req"
version = "0.3.1"
description = "⚡ High-performance async HTTP client in Rust with Python bindings for blazing-fast batch requests."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [ "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Rust", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent",]
[[project.authors]]
name = "KAY53N"
email = "kaysen820@gmail.com"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/KAY53N/rusty-req"
Repository = "https://github.com/KAY53N/rusty-req"
"Bug Tracker" = "https://github.com/KAY53N/rusty-req/issues"
Documentation = "https://github.com/KAY53N/rusty-req#readme"

[tool.maturin]
bindings = "pyo3"
module-name = "rusty_req"
