[build-system]
requires = [ "maturin>=1.4,<2.0",]
build-backend = "maturin"

[project]
name = "rusty-req"
version = "0.1.8"
description = "High-performance async HTTP client built with Rust for Python."
readme = "README.md"
license = "MIT"
requires-python = ">=3.7"
classifiers = [ "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Rust", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent",]
[[project.authors]]
name = "KAY53N"
email = "kaysen820@gmail.com"

[project.urls]
Homepage = "https://github.com/KAY53N/rusty-req"
Repository = "https://github.com/KAY53N/rusty-req"
"Bug Tracker" = "https://github.com/KAY53N/rusty-req/issues"
Documentation = "https://github.com/KAY53N/rusty-req#readme"

[tool.maturin]
bindings = "pyo3"
module-name = "rusty_req"
