name: Performance Benchmark

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Start httpbin Docker service
      run: |
        docker run -d --name httpbin -p 8080:80 kennethreitz/httpbin:latest
        # Wait for service to start
        sleep 10
        # Verify service is running
        curl -f http://localhost:8080/status/200
    
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rusty-req aiohttp httpx requests psutil
    
    - name: Run performance tests
      run: python tests/performance_test.py
      env:
        HTTPBIN_URL: http://localhost:8080
    
    - name: Stop httpbin service
      run: |
        docker stop httpbin
        docker rm httpbin

